# Nacos配置示例 - gRPC配置
# 在Nacos中创建配置：
# Data ID: global.yaml 或各服务专用配置
# Group: DEFAULT_GROUP

# gRPC配置
grpc:
  # 服务器配置（仅im-connect-service需要）
  server:
    port: 9091  # im-connect-service的gRPC服务器端口
    max-inbound-message-size: 1048576  # 1MB
    max-inbound-metadata-size: 8192    # 8KB
    keep-alive-time: 30
    keep-alive-timeout: 5
    permit-keep-alive-without-calls: true
  
  # 客户端配置（所有服务都需要）
  client:
    default-port: 9091  # 连接到im-connect-service的gRPC端口
    connect-timeout: 10
    keep-alive-time: 30
    keep-alive-timeout: 5
    max-inbound-message-size: 1048576
    permit-keep-alive-without-calls: true
