{
 "title": "im-connect  服务指标",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "threads_metrics",
    "query": {
     "query": "label_values({__name__=~\"jvm_threads_.*\"}, __name__)"
    }
   },
   {
    "name": "memory_pool_metrics",
    "query": {
     "query": "label_values({__name__=~\"jvm_memory_pool_.*\"}, pool)"
    }
   },
   {
    "name": "memory_area_metrics",
    "query": {
     "query": "label_values({__name__=~\"jvm_memory_bytes_*\"}, area)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_total{job=\"im-connect\"}",
     "legendFormat": "系统总内存"
    },
    {
     "expr": "system_memory_free{job=\"im-connect\"}",
     "legendFormat": "空闲内存"
    },
    {
     "expr": "system_memory_total - system_memory_free",
     "legendFormat": "已使用内存"
    }
   ]
  },
  {
   "title": "进程cpu使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"im-connect\"}[1m])"
    },
    {}
   ]
  },
  {
   "title": "进程描述符使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_max_fds{job=\"im-connect\"}",
     "legendFormat": "最大描述符数量"
    },
    {
     "expr": "process_open_fds{job=\"im-connect\"}",
     "legendFormat": "打开的描述符数量"
    }
   ]
  },
  {
   "title": "线程状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_threads_state{job=\"im-connect\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "内存池信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_memory_bytes_used|jvm_memory_bytes_committed|jvm_memory_bytes_max|jvm_memory_bytes_init\", area=~\"$memory_area_metrics\"}\n",
     "legendFormat": "{{__name__}} - {{area}}"
    }
   ]
  },
  {
   "title": "gc信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"im-connect\"} ",
     "legendFormat": "gc回收次数-{{gc}}"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{job=\"im-connect\"}",
     "legendFormat": "gc回收总次数-{{gc}}"
    }
   ]
  },
  {
   "title": "堆内存信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "repeat": "memory_pool_metrics",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_memory_pool_bytes_.*\", pool=~\"CodeHeap 'non-nmethods'|Metaspace|CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "线程信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "repeat": "threads_metrics",
   "targets": [
    {
     "expr": "sum({__name__=~\"jvm_threads_.*\", __name__!~\"jvm_threads_state.*\"}) by (__name__)  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "类加载信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "jvm_classes_currently_loaded ", "legendFormat": "当前加载类总数" },
    { "expr": " jvm_classes_loaded_total ", "legendFormat": "总共加载类数量" },
    { "expr": "jvm_classes_unloaded_total", "legendFormat": "卸载类数量" }
   ]
  }
 ]
}