// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

package com.xzll.connect.grpc;

public final class MessageServiceProto {
  private MessageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_TransferC2CMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_TransferC2CMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_ServerAckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_ClientAckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_ClientAckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_WithdrawMsgRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_WithdrawMsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzll_connect_grpc_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzll_connect_grpc_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025message_service.proto\022\025com.xzll.connec" +
      "t.grpc\"\303\001\n\031TransferC2CMessageRequest\022\013\n\003" +
      "url\030\001 \001(\t\022\014\n\004body\030\002 \001(\t\022\024\n\014from_user_id\030" +
      "\003 \001(\t\022\022\n\nto_user_id\030\004 \001(\t\022\016\n\006msg_id\030\005 \001(" +
      "\t\022\023\n\013msg_content\030\006 \001(\t\022\022\n\nmsg_format\030\007 \001" +
      "(\t\022\027\n\017msg_create_time\030\010 \001(\003\022\017\n\007chat_id\030\t" +
      " \001(\t\"I\n\032TransferC2CMessageResponse\022\014\n\004co" +
      "de\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\"" +
      "\236\001\n\020ServerAckRequest\022\016\n\006msg_id\030\001 \001(\t\022\017\n\007" +
      "chat_id\030\002 \001(\t\022\022\n\nto_user_id\030\003 \001(\t\022\025\n\rack" +
      "_text_desc\030\004 \001(\t\022\033\n\023msg_received_status\030" +
      "\005 \001(\005\022\024\n\014receive_time\030\006 \001(\003\022\013\n\003url\030\007 \001(\t" +
      "\"\236\001\n\020ClientAckRequest\022\016\n\006msg_id\030\001 \001(\t\022\017\n" +
      "\007chat_id\030\002 \001(\t\022\022\n\nto_user_id\030\003 \001(\t\022\025\n\rac" +
      "k_text_desc\030\004 \001(\t\022\033\n\023msg_received_status" +
      "\030\005 \001(\005\022\024\n\014receive_time\030\006 \001(\003\022\013\n\003url\030\007 \001(" +
      "\t\"V\n\022WithdrawMsgRequest\022\016\n\006msg_id\030\001 \001(\t\022" +
      "\017\n\007chat_id\030\002 \001(\t\022\022\n\nto_user_id\030\003 \001(\t\022\013\n\003" +
      "url\030\004 \001(\t\">\n\017MessageResponse\022\014\n\004code\030\001 \001" +
      "(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\t2\223\001\n\026Me" +
      "ssageTransferService\022y\n\022TransferC2CMessa" +
      "ge\0220.com.xzll.connect.grpc.TransferC2CMe" +
      "ssageRequest\0321.com.xzll.connect.grpc.Tra" +
      "nsferC2CMessageResponse2\335\002\n\024ClientMessag" +
      "eService\022k\n\030ResponseServerAck2Client\022\'.c" +
      "om.xzll.connect.grpc.ServerAckRequest\032&." +
      "com.xzll.connect.grpc.MessageResponse\022k\n" +
      "\030ResponseClientAck2Client\022\'.com.xzll.con" +
      "nect.grpc.ClientAckRequest\032&.com.xzll.co" +
      "nnect.grpc.MessageResponse\022k\n\026SendWithdr" +
      "awMsg2Client\022).com.xzll.connect.grpc.Wit" +
      "hdrawMsgRequest\032&.com.xzll.connect.grpc." +
      "MessageResponseB.\n\025com.xzll.connect.grpc" +
      "B\023MessageServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor,
        new java.lang.String[] { "Url", "Body", "FromUserId", "ToUserId", "MsgId", "MsgContent", "MsgFormat", "MsgCreateTime", "ChatId", });
    internal_static_com_xzll_connect_grpc_TransferC2CMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xzll_connect_grpc_TransferC2CMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_TransferC2CMessageResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xzll_connect_grpc_ServerAckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor,
        new java.lang.String[] { "MsgId", "ChatId", "ToUserId", "AckTextDesc", "MsgReceivedStatus", "ReceiveTime", "Url", });
    internal_static_com_xzll_connect_grpc_ClientAckRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_xzll_connect_grpc_ClientAckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_ClientAckRequest_descriptor,
        new java.lang.String[] { "MsgId", "ChatId", "ToUserId", "AckTextDesc", "MsgReceivedStatus", "ReceiveTime", "Url", });
    internal_static_com_xzll_connect_grpc_WithdrawMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_xzll_connect_grpc_WithdrawMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_WithdrawMsgRequest_descriptor,
        new java.lang.String[] { "MsgId", "ChatId", "ToUserId", "Url", });
    internal_static_com_xzll_connect_grpc_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_xzll_connect_grpc_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzll_connect_grpc_MessageResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
