// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

package com.xzll.connect.grpc;

public interface ServerAckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xzll.connect.grpc.ServerAckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg_id = 1;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <code>string msg_id = 1;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string chat_id = 2;</code>
   * @return The chatId.
   */
  java.lang.String getChatId();
  /**
   * <code>string chat_id = 2;</code>
   * @return The bytes for chatId.
   */
  com.google.protobuf.ByteString
      getChatIdBytes();

  /**
   * <code>string to_user_id = 3;</code>
   * @return The toUserId.
   */
  java.lang.String getToUserId();
  /**
   * <code>string to_user_id = 3;</code>
   * @return The bytes for toUserId.
   */
  com.google.protobuf.ByteString
      getToUserIdBytes();

  /**
   * <code>string ack_text_desc = 4;</code>
   * @return The ackTextDesc.
   */
  java.lang.String getAckTextDesc();
  /**
   * <code>string ack_text_desc = 4;</code>
   * @return The bytes for ackTextDesc.
   */
  com.google.protobuf.ByteString
      getAckTextDescBytes();

  /**
   * <code>int32 msg_received_status = 5;</code>
   * @return The msgReceivedStatus.
   */
  int getMsgReceivedStatus();

  /**
   * <code>int64 receive_time = 6;</code>
   * @return The receiveTime.
   */
  long getReceiveTime();

  /**
   * <code>string url = 7;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 7;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
