// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

package com.xzll.connect.grpc;

/**
 * <pre>
 * 服务端ACK请求
 * </pre>
 *
 * Protobuf type {@code com.xzll.connect.grpc.ServerAckRequest}
 */
public final class ServerAckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xzll.connect.grpc.ServerAckRequest)
    ServerAckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerAckRequest.newBuilder() to construct.
  private ServerAckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerAckRequest() {
    msgId_ = "";
    chatId_ = "";
    toUserId_ = "";
    ackTextDesc_ = "";
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerAckRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerAckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            msgId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            chatId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            toUserId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ackTextDesc_ = s;
            break;
          }
          case 40: {

            msgReceivedStatus_ = input.readInt32();
            break;
          }
          case 48: {

            receiveTime_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_ServerAckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xzll.connect.grpc.ServerAckRequest.class, com.xzll.connect.grpc.ServerAckRequest.Builder.class);
  }

  public static final int MSG_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgId_;
  /**
   * <code>string msg_id = 1;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public java.lang.String getMsgId() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_id = 1;</code>
   * @return The bytes for msgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object chatId_;
  /**
   * <code>string chat_id = 2;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public java.lang.String getChatId() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatId_ = s;
      return s;
    }
  }
  /**
   * <code>string chat_id = 2;</code>
   * @return The bytes for chatId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatIdBytes() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_USER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object toUserId_;
  /**
   * <code>string to_user_id = 3;</code>
   * @return The toUserId.
   */
  @java.lang.Override
  public java.lang.String getToUserId() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string to_user_id = 3;</code>
   * @return The bytes for toUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToUserIdBytes() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACK_TEXT_DESC_FIELD_NUMBER = 4;
  private volatile java.lang.Object ackTextDesc_;
  /**
   * <code>string ack_text_desc = 4;</code>
   * @return The ackTextDesc.
   */
  @java.lang.Override
  public java.lang.String getAckTextDesc() {
    java.lang.Object ref = ackTextDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ackTextDesc_ = s;
      return s;
    }
  }
  /**
   * <code>string ack_text_desc = 4;</code>
   * @return The bytes for ackTextDesc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAckTextDescBytes() {
    java.lang.Object ref = ackTextDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ackTextDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_RECEIVED_STATUS_FIELD_NUMBER = 5;
  private int msgReceivedStatus_;
  /**
   * <code>int32 msg_received_status = 5;</code>
   * @return The msgReceivedStatus.
   */
  @java.lang.Override
  public int getMsgReceivedStatus() {
    return msgReceivedStatus_;
  }

  public static final int RECEIVE_TIME_FIELD_NUMBER = 6;
  private long receiveTime_;
  /**
   * <code>int64 receive_time = 6;</code>
   * @return The receiveTime.
   */
  @java.lang.Override
  public long getReceiveTime() {
    return receiveTime_;
  }

  public static final int URL_FIELD_NUMBER = 7;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 7;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 7;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMsgIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
    }
    if (!getChatIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chatId_);
    }
    if (!getToUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toUserId_);
    }
    if (!getAckTextDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ackTextDesc_);
    }
    if (msgReceivedStatus_ != 0) {
      output.writeInt32(5, msgReceivedStatus_);
    }
    if (receiveTime_ != 0L) {
      output.writeInt64(6, receiveTime_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, url_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMsgIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
    }
    if (!getChatIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chatId_);
    }
    if (!getToUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toUserId_);
    }
    if (!getAckTextDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ackTextDesc_);
    }
    if (msgReceivedStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, msgReceivedStatus_);
    }
    if (receiveTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, receiveTime_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, url_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xzll.connect.grpc.ServerAckRequest)) {
      return super.equals(obj);
    }
    com.xzll.connect.grpc.ServerAckRequest other = (com.xzll.connect.grpc.ServerAckRequest) obj;

    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (!getChatId()
        .equals(other.getChatId())) return false;
    if (!getToUserId()
        .equals(other.getToUserId())) return false;
    if (!getAckTextDesc()
        .equals(other.getAckTextDesc())) return false;
    if (getMsgReceivedStatus()
        != other.getMsgReceivedStatus()) return false;
    if (getReceiveTime()
        != other.getReceiveTime()) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChatId().hashCode();
    hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getToUserId().hashCode();
    hash = (37 * hash) + ACK_TEXT_DESC_FIELD_NUMBER;
    hash = (53 * hash) + getAckTextDesc().hashCode();
    hash = (37 * hash) + MSG_RECEIVED_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getMsgReceivedStatus();
    hash = (37 * hash) + RECEIVE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiveTime());
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.ServerAckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xzll.connect.grpc.ServerAckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 服务端ACK请求
   * </pre>
   *
   * Protobuf type {@code com.xzll.connect.grpc.ServerAckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xzll.connect.grpc.ServerAckRequest)
      com.xzll.connect.grpc.ServerAckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_ServerAckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xzll.connect.grpc.ServerAckRequest.class, com.xzll.connect.grpc.ServerAckRequest.Builder.class);
    }

    // Construct using com.xzll.connect.grpc.ServerAckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgId_ = "";

      chatId_ = "";

      toUserId_ = "";

      ackTextDesc_ = "";

      msgReceivedStatus_ = 0;

      receiveTime_ = 0L;

      url_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_ServerAckRequest_descriptor;
    }

    @java.lang.Override
    public com.xzll.connect.grpc.ServerAckRequest getDefaultInstanceForType() {
      return com.xzll.connect.grpc.ServerAckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xzll.connect.grpc.ServerAckRequest build() {
      com.xzll.connect.grpc.ServerAckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xzll.connect.grpc.ServerAckRequest buildPartial() {
      com.xzll.connect.grpc.ServerAckRequest result = new com.xzll.connect.grpc.ServerAckRequest(this);
      result.msgId_ = msgId_;
      result.chatId_ = chatId_;
      result.toUserId_ = toUserId_;
      result.ackTextDesc_ = ackTextDesc_;
      result.msgReceivedStatus_ = msgReceivedStatus_;
      result.receiveTime_ = receiveTime_;
      result.url_ = url_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xzll.connect.grpc.ServerAckRequest) {
        return mergeFrom((com.xzll.connect.grpc.ServerAckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xzll.connect.grpc.ServerAckRequest other) {
      if (other == com.xzll.connect.grpc.ServerAckRequest.getDefaultInstance()) return this;
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        onChanged();
      }
      if (!other.getChatId().isEmpty()) {
        chatId_ = other.chatId_;
        onChanged();
      }
      if (!other.getToUserId().isEmpty()) {
        toUserId_ = other.toUserId_;
        onChanged();
      }
      if (!other.getAckTextDesc().isEmpty()) {
        ackTextDesc_ = other.ackTextDesc_;
        onChanged();
      }
      if (other.getMsgReceivedStatus() != 0) {
        setMsgReceivedStatus(other.getMsgReceivedStatus());
      }
      if (other.getReceiveTime() != 0L) {
        setReceiveTime(other.getReceiveTime());
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xzll.connect.grpc.ServerAckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xzll.connect.grpc.ServerAckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object msgId_ = "";
    /**
     * <code>string msg_id = 1;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_id = 1;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_id = 1;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      
      msgId_ = getDefaultInstance().getMsgId();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_id = 1;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chatId_ = "";
    /**
     * <code>string chat_id = 2;</code>
     * @return The chatId.
     */
    public java.lang.String getChatId() {
      java.lang.Object ref = chatId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chat_id = 2;</code>
     * @return The bytes for chatId.
     */
    public com.google.protobuf.ByteString
        getChatIdBytes() {
      java.lang.Object ref = chatId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chat_id = 2;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chat_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      
      chatId_ = getDefaultInstance().getChatId();
      onChanged();
      return this;
    }
    /**
     * <code>string chat_id = 2;</code>
     * @param value The bytes for chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toUserId_ = "";
    /**
     * <code>string to_user_id = 3;</code>
     * @return The toUserId.
     */
    public java.lang.String getToUserId() {
      java.lang.Object ref = toUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string to_user_id = 3;</code>
     * @return The bytes for toUserId.
     */
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to_user_id = 3;</code>
     * @param value The toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to_user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToUserId() {
      
      toUserId_ = getDefaultInstance().getToUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string to_user_id = 3;</code>
     * @param value The bytes for toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ackTextDesc_ = "";
    /**
     * <code>string ack_text_desc = 4;</code>
     * @return The ackTextDesc.
     */
    public java.lang.String getAckTextDesc() {
      java.lang.Object ref = ackTextDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ackTextDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ack_text_desc = 4;</code>
     * @return The bytes for ackTextDesc.
     */
    public com.google.protobuf.ByteString
        getAckTextDescBytes() {
      java.lang.Object ref = ackTextDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ackTextDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ack_text_desc = 4;</code>
     * @param value The ackTextDesc to set.
     * @return This builder for chaining.
     */
    public Builder setAckTextDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ackTextDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ack_text_desc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAckTextDesc() {
      
      ackTextDesc_ = getDefaultInstance().getAckTextDesc();
      onChanged();
      return this;
    }
    /**
     * <code>string ack_text_desc = 4;</code>
     * @param value The bytes for ackTextDesc to set.
     * @return This builder for chaining.
     */
    public Builder setAckTextDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ackTextDesc_ = value;
      onChanged();
      return this;
    }

    private int msgReceivedStatus_ ;
    /**
     * <code>int32 msg_received_status = 5;</code>
     * @return The msgReceivedStatus.
     */
    @java.lang.Override
    public int getMsgReceivedStatus() {
      return msgReceivedStatus_;
    }
    /**
     * <code>int32 msg_received_status = 5;</code>
     * @param value The msgReceivedStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMsgReceivedStatus(int value) {
      
      msgReceivedStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msg_received_status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgReceivedStatus() {
      
      msgReceivedStatus_ = 0;
      onChanged();
      return this;
    }

    private long receiveTime_ ;
    /**
     * <code>int64 receive_time = 6;</code>
     * @return The receiveTime.
     */
    @java.lang.Override
    public long getReceiveTime() {
      return receiveTime_;
    }
    /**
     * <code>int64 receive_time = 6;</code>
     * @param value The receiveTime to set.
     * @return This builder for chaining.
     */
    public Builder setReceiveTime(long value) {
      
      receiveTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 receive_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiveTime() {
      
      receiveTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 7;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 7;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 7;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 7;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xzll.connect.grpc.ServerAckRequest)
  }

  // @@protoc_insertion_point(class_scope:com.xzll.connect.grpc.ServerAckRequest)
  private static final com.xzll.connect.grpc.ServerAckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xzll.connect.grpc.ServerAckRequest();
  }

  public static com.xzll.connect.grpc.ServerAckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerAckRequest>
      PARSER = new com.google.protobuf.AbstractParser<ServerAckRequest>() {
    @java.lang.Override
    public ServerAckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerAckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerAckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerAckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xzll.connect.grpc.ServerAckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

