// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

package com.xzll.connect.grpc;

public interface TransferC2CMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xzll.connect.grpc.TransferC2CMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string from_user_id = 3;</code>
   * @return The fromUserId.
   */
  java.lang.String getFromUserId();
  /**
   * <code>string from_user_id = 3;</code>
   * @return The bytes for fromUserId.
   */
  com.google.protobuf.ByteString
      getFromUserIdBytes();

  /**
   * <code>string to_user_id = 4;</code>
   * @return The toUserId.
   */
  java.lang.String getToUserId();
  /**
   * <code>string to_user_id = 4;</code>
   * @return The bytes for toUserId.
   */
  com.google.protobuf.ByteString
      getToUserIdBytes();

  /**
   * <code>string msg_id = 5;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <code>string msg_id = 5;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string msg_content = 6;</code>
   * @return The msgContent.
   */
  java.lang.String getMsgContent();
  /**
   * <code>string msg_content = 6;</code>
   * @return The bytes for msgContent.
   */
  com.google.protobuf.ByteString
      getMsgContentBytes();

  /**
   * <code>string msg_format = 7;</code>
   * @return The msgFormat.
   */
  java.lang.String getMsgFormat();
  /**
   * <code>string msg_format = 7;</code>
   * @return The bytes for msgFormat.
   */
  com.google.protobuf.ByteString
      getMsgFormatBytes();

  /**
   * <code>int64 msg_create_time = 8;</code>
   * @return The msgCreateTime.
   */
  long getMsgCreateTime();

  /**
   * <code>string chat_id = 9;</code>
   * @return The chatId.
   */
  java.lang.String getChatId();
  /**
   * <code>string chat_id = 9;</code>
   * @return The bytes for chatId.
   */
  com.google.protobuf.ByteString
      getChatIdBytes();
}
