// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

package com.xzll.connect.grpc;

/**
 * <pre>
 * 转发C2C消息请求
 * </pre>
 *
 * Protobuf type {@code com.xzll.connect.grpc.TransferC2CMessageRequest}
 */
public final class TransferC2CMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xzll.connect.grpc.TransferC2CMessageRequest)
    TransferC2CMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransferC2CMessageRequest.newBuilder() to construct.
  private TransferC2CMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransferC2CMessageRequest() {
    url_ = "";
    body_ = "";
    fromUserId_ = "";
    toUserId_ = "";
    msgId_ = "";
    msgContent_ = "";
    msgFormat_ = "";
    chatId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransferC2CMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransferC2CMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            fromUserId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            toUserId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            msgId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            msgContent_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            msgFormat_ = s;
            break;
          }
          case 64: {

            msgCreateTime_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            chatId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xzll.connect.grpc.TransferC2CMessageRequest.class, com.xzll.connect.grpc.TransferC2CMessageRequest.Builder.class);
  }

  public static final int URL_FIELD_NUMBER = 1;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private volatile java.lang.Object body_;
  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_USER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object fromUserId_;
  /**
   * <code>string from_user_id = 3;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public java.lang.String getFromUserId() {
    java.lang.Object ref = fromUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string from_user_id = 3;</code>
   * @return The bytes for fromUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromUserIdBytes() {
    java.lang.Object ref = fromUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_USER_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object toUserId_;
  /**
   * <code>string to_user_id = 4;</code>
   * @return The toUserId.
   */
  @java.lang.Override
  public java.lang.String getToUserId() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string to_user_id = 4;</code>
   * @return The bytes for toUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToUserIdBytes() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object msgId_;
  /**
   * <code>string msg_id = 5;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public java.lang.String getMsgId() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_id = 5;</code>
   * @return The bytes for msgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_CONTENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object msgContent_;
  /**
   * <code>string msg_content = 6;</code>
   * @return The msgContent.
   */
  @java.lang.Override
  public java.lang.String getMsgContent() {
    java.lang.Object ref = msgContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgContent_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_content = 6;</code>
   * @return The bytes for msgContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgContentBytes() {
    java.lang.Object ref = msgContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_FORMAT_FIELD_NUMBER = 7;
  private volatile java.lang.Object msgFormat_;
  /**
   * <code>string msg_format = 7;</code>
   * @return The msgFormat.
   */
  @java.lang.Override
  public java.lang.String getMsgFormat() {
    java.lang.Object ref = msgFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgFormat_ = s;
      return s;
    }
  }
  /**
   * <code>string msg_format = 7;</code>
   * @return The bytes for msgFormat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgFormatBytes() {
    java.lang.Object ref = msgFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_CREATE_TIME_FIELD_NUMBER = 8;
  private long msgCreateTime_;
  /**
   * <code>int64 msg_create_time = 8;</code>
   * @return The msgCreateTime.
   */
  @java.lang.Override
  public long getMsgCreateTime() {
    return msgCreateTime_;
  }

  public static final int CHAT_ID_FIELD_NUMBER = 9;
  private volatile java.lang.Object chatId_;
  /**
   * <code>string chat_id = 9;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public java.lang.String getChatId() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatId_ = s;
      return s;
    }
  }
  /**
   * <code>string chat_id = 9;</code>
   * @return The bytes for chatId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatIdBytes() {
    java.lang.Object ref = chatId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
    }
    if (!getBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
    }
    if (!getFromUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromUserId_);
    }
    if (!getToUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toUserId_);
    }
    if (!getMsgIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgId_);
    }
    if (!getMsgContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msgContent_);
    }
    if (!getMsgFormatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgFormat_);
    }
    if (msgCreateTime_ != 0L) {
      output.writeInt64(8, msgCreateTime_);
    }
    if (!getChatIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, chatId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
    }
    if (!getBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
    }
    if (!getFromUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromUserId_);
    }
    if (!getToUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toUserId_);
    }
    if (!getMsgIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgId_);
    }
    if (!getMsgContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msgContent_);
    }
    if (!getMsgFormatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgFormat_);
    }
    if (msgCreateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, msgCreateTime_);
    }
    if (!getChatIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, chatId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xzll.connect.grpc.TransferC2CMessageRequest)) {
      return super.equals(obj);
    }
    com.xzll.connect.grpc.TransferC2CMessageRequest other = (com.xzll.connect.grpc.TransferC2CMessageRequest) obj;

    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getFromUserId()
        .equals(other.getFromUserId())) return false;
    if (!getToUserId()
        .equals(other.getToUserId())) return false;
    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (!getMsgContent()
        .equals(other.getMsgContent())) return false;
    if (!getMsgFormat()
        .equals(other.getMsgFormat())) return false;
    if (getMsgCreateTime()
        != other.getMsgCreateTime()) return false;
    if (!getChatId()
        .equals(other.getChatId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + FROM_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFromUserId().hashCode();
    hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getToUserId().hashCode();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (37 * hash) + MSG_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getMsgContent().hashCode();
    hash = (37 * hash) + MSG_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getMsgFormat().hashCode();
    hash = (37 * hash) + MSG_CREATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgCreateTime());
    hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChatId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xzll.connect.grpc.TransferC2CMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xzll.connect.grpc.TransferC2CMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 转发C2C消息请求
   * </pre>
   *
   * Protobuf type {@code com.xzll.connect.grpc.TransferC2CMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xzll.connect.grpc.TransferC2CMessageRequest)
      com.xzll.connect.grpc.TransferC2CMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xzll.connect.grpc.TransferC2CMessageRequest.class, com.xzll.connect.grpc.TransferC2CMessageRequest.Builder.class);
    }

    // Construct using com.xzll.connect.grpc.TransferC2CMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      url_ = "";

      body_ = "";

      fromUserId_ = "";

      toUserId_ = "";

      msgId_ = "";

      msgContent_ = "";

      msgFormat_ = "";

      msgCreateTime_ = 0L;

      chatId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xzll.connect.grpc.MessageServiceProto.internal_static_com_xzll_connect_grpc_TransferC2CMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.xzll.connect.grpc.TransferC2CMessageRequest getDefaultInstanceForType() {
      return com.xzll.connect.grpc.TransferC2CMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xzll.connect.grpc.TransferC2CMessageRequest build() {
      com.xzll.connect.grpc.TransferC2CMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xzll.connect.grpc.TransferC2CMessageRequest buildPartial() {
      com.xzll.connect.grpc.TransferC2CMessageRequest result = new com.xzll.connect.grpc.TransferC2CMessageRequest(this);
      result.url_ = url_;
      result.body_ = body_;
      result.fromUserId_ = fromUserId_;
      result.toUserId_ = toUserId_;
      result.msgId_ = msgId_;
      result.msgContent_ = msgContent_;
      result.msgFormat_ = msgFormat_;
      result.msgCreateTime_ = msgCreateTime_;
      result.chatId_ = chatId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xzll.connect.grpc.TransferC2CMessageRequest) {
        return mergeFrom((com.xzll.connect.grpc.TransferC2CMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xzll.connect.grpc.TransferC2CMessageRequest other) {
      if (other == com.xzll.connect.grpc.TransferC2CMessageRequest.getDefaultInstance()) return this;
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getFromUserId().isEmpty()) {
        fromUserId_ = other.fromUserId_;
        onChanged();
      }
      if (!other.getToUserId().isEmpty()) {
        toUserId_ = other.toUserId_;
        onChanged();
      }
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        onChanged();
      }
      if (!other.getMsgContent().isEmpty()) {
        msgContent_ = other.msgContent_;
        onChanged();
      }
      if (!other.getMsgFormat().isEmpty()) {
        msgFormat_ = other.msgFormat_;
        onChanged();
      }
      if (other.getMsgCreateTime() != 0L) {
        setMsgCreateTime(other.getMsgCreateTime());
      }
      if (!other.getChatId().isEmpty()) {
        chatId_ = other.chatId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xzll.connect.grpc.TransferC2CMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xzll.connect.grpc.TransferC2CMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 1;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 1;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 2;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 2;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 2;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <code>string body = 2;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fromUserId_ = "";
    /**
     * <code>string from_user_id = 3;</code>
     * @return The fromUserId.
     */
    public java.lang.String getFromUserId() {
      java.lang.Object ref = fromUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from_user_id = 3;</code>
     * @return The bytes for fromUserId.
     */
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from_user_id = 3;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from_user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      
      fromUserId_ = getDefaultInstance().getFromUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string from_user_id = 3;</code>
     * @param value The bytes for fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toUserId_ = "";
    /**
     * <code>string to_user_id = 4;</code>
     * @return The toUserId.
     */
    public java.lang.String getToUserId() {
      java.lang.Object ref = toUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string to_user_id = 4;</code>
     * @return The bytes for toUserId.
     */
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to_user_id = 4;</code>
     * @param value The toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to_user_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToUserId() {
      
      toUserId_ = getDefaultInstance().getToUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string to_user_id = 4;</code>
     * @param value The bytes for toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgId_ = "";
    /**
     * <code>string msg_id = 5;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_id = 5;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_id = 5;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      
      msgId_ = getDefaultInstance().getMsgId();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_id = 5;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgContent_ = "";
    /**
     * <code>string msg_content = 6;</code>
     * @return The msgContent.
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_content = 6;</code>
     * @return The bytes for msgContent.
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_content = 6;</code>
     * @param value The msgContent to set.
     * @return This builder for chaining.
     */
    public Builder setMsgContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_content = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgContent() {
      
      msgContent_ = getDefaultInstance().getMsgContent();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_content = 6;</code>
     * @param value The bytes for msgContent to set.
     * @return This builder for chaining.
     */
    public Builder setMsgContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgContent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgFormat_ = "";
    /**
     * <code>string msg_format = 7;</code>
     * @return The msgFormat.
     */
    public java.lang.String getMsgFormat() {
      java.lang.Object ref = msgFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg_format = 7;</code>
     * @return The bytes for msgFormat.
     */
    public com.google.protobuf.ByteString
        getMsgFormatBytes() {
      java.lang.Object ref = msgFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg_format = 7;</code>
     * @param value The msgFormat to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFormat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg_format = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgFormat() {
      
      msgFormat_ = getDefaultInstance().getMsgFormat();
      onChanged();
      return this;
    }
    /**
     * <code>string msg_format = 7;</code>
     * @param value The bytes for msgFormat to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgFormat_ = value;
      onChanged();
      return this;
    }

    private long msgCreateTime_ ;
    /**
     * <code>int64 msg_create_time = 8;</code>
     * @return The msgCreateTime.
     */
    @java.lang.Override
    public long getMsgCreateTime() {
      return msgCreateTime_;
    }
    /**
     * <code>int64 msg_create_time = 8;</code>
     * @param value The msgCreateTime to set.
     * @return This builder for chaining.
     */
    public Builder setMsgCreateTime(long value) {
      
      msgCreateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 msg_create_time = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgCreateTime() {
      
      msgCreateTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object chatId_ = "";
    /**
     * <code>string chat_id = 9;</code>
     * @return The chatId.
     */
    public java.lang.String getChatId() {
      java.lang.Object ref = chatId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chat_id = 9;</code>
     * @return The bytes for chatId.
     */
    public com.google.protobuf.ByteString
        getChatIdBytes() {
      java.lang.Object ref = chatId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chat_id = 9;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chat_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      
      chatId_ = getDefaultInstance().getChatId();
      onChanged();
      return this;
    }
    /**
     * <code>string chat_id = 9;</code>
     * @param value The bytes for chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xzll.connect.grpc.TransferC2CMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:com.xzll.connect.grpc.TransferC2CMessageRequest)
  private static final com.xzll.connect.grpc.TransferC2CMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xzll.connect.grpc.TransferC2CMessageRequest();
  }

  public static com.xzll.connect.grpc.TransferC2CMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransferC2CMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransferC2CMessageRequest>() {
    @java.lang.Override
    public TransferC2CMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransferC2CMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransferC2CMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransferC2CMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xzll.connect.grpc.TransferC2CMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

