// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: proto/message_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举（扩展版，兼容Go代码）
type MsgType int32

const (
	MsgType_MSG_TYPE_UNKNOWN MsgType = 0
	// ========== 单聊相关 ==========
	MsgType_C2C_SEND     MsgType = 1 // C2C发送消息（上行）
	MsgType_C2C_ACK      MsgType = 2 // C2C消息确认（上行/下行）
	MsgType_C2C_WITHDRAW MsgType = 3 // C2C撤回消息（上行/下行）
	MsgType_C2C_MSG_PUSH MsgType = 5 // 服务端推送单聊消息（下行）
	// ========== 消息确认和撤回（扩展） ==========
	MsgType_CLIENT_RECEIVED_MSG_ACK   MsgType = 13 // 客户端消息确认（上行）
	MsgType_WITHDRAW_MSG_SEND         MsgType = 14 // 撤回消息发送（上行）
	MsgType_WITHDRAW_MSG_RESPONSE     MsgType = 15 // 撤回消息响应（下行）
	MsgType_MSG_DELIVERY_NOTIFICATION MsgType = 16 // 消息送达通知（下行）
	MsgType_MSG_WITHDRAW_NOTIFICATION MsgType = 17 // 消息撤回通知（下行）
	// ========== 服务器相关 ==========
	MsgType_SERVER_ACK MsgType = 18 // 服务器确认（下行）
	MsgType_HEARTBEAT  MsgType = 19 // 心跳消息（上行/下行）
	// ========== 群聊相关（预留，暂未实现） ==========
	MsgType_GROUP_SEND     MsgType = 7  // 群聊发送消息（上行）
	MsgType_GROUP_MSG_PUSH MsgType = 8  // 服务端推送群聊消息（下行）
	MsgType_GROUP_ACK      MsgType = 9  // 群聊消息确认（上行）
	MsgType_GROUP_WITHDRAW MsgType = 10 // 群聊撤回消息（上行/下行）
	// ========== 好友相关 ==========
	MsgType_FRIEND_REQUEST  MsgType = 11 // 好友请求推送（下行）
	MsgType_FRIEND_RESPONSE MsgType = 12 // 好友响应推送（下行）
	// ========== 通用功能 ==========
	MsgType_GET_BATCH_MSG_IDS  MsgType = 4 // 批量获取消息ID（上行）
	MsgType_PUSH_BATCH_MSG_IDS MsgType = 6 // 服务端推送消息ID列表（下行）
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "MSG_TYPE_UNKNOWN",
		1:  "C2C_SEND",
		2:  "C2C_ACK",
		3:  "C2C_WITHDRAW",
		5:  "C2C_MSG_PUSH",
		13: "CLIENT_RECEIVED_MSG_ACK",
		14: "WITHDRAW_MSG_SEND",
		15: "WITHDRAW_MSG_RESPONSE",
		16: "MSG_DELIVERY_NOTIFICATION",
		17: "MSG_WITHDRAW_NOTIFICATION",
		18: "SERVER_ACK",
		19: "HEARTBEAT",
		7:  "GROUP_SEND",
		8:  "GROUP_MSG_PUSH",
		9:  "GROUP_ACK",
		10: "GROUP_WITHDRAW",
		11: "FRIEND_REQUEST",
		12: "FRIEND_RESPONSE",
		4:  "GET_BATCH_MSG_IDS",
		6:  "PUSH_BATCH_MSG_IDS",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNKNOWN":          0,
		"C2C_SEND":                  1,
		"C2C_ACK":                   2,
		"C2C_WITHDRAW":              3,
		"C2C_MSG_PUSH":              5,
		"CLIENT_RECEIVED_MSG_ACK":   13,
		"WITHDRAW_MSG_SEND":         14,
		"WITHDRAW_MSG_RESPONSE":     15,
		"MSG_DELIVERY_NOTIFICATION": 16,
		"MSG_WITHDRAW_NOTIFICATION": 17,
		"SERVER_ACK":                18,
		"HEARTBEAT":                 19,
		"GROUP_SEND":                7,
		"GROUP_MSG_PUSH":            8,
		"GROUP_ACK":                 9,
		"GROUP_WITHDRAW":            10,
		"FRIEND_REQUEST":            11,
		"FRIEND_RESPONSE":           12,
		"GET_BATCH_MSG_IDS":         4,
		"PUSH_BATCH_MSG_IDS":        6,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_service_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_message_service_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{0}
}

// Protobuf 响应码枚举
type ProtoResponseCode int32

const (
	ProtoResponseCode_SUCCESS             ProtoResponseCode = 0   // 成功
	ProtoResponseCode_INVALID_REQUEST     ProtoResponseCode = 400 // 无效请求
	ProtoResponseCode_UNAUTHORIZED        ProtoResponseCode = 401 // 未授权
	ProtoResponseCode_FORBIDDEN           ProtoResponseCode = 403 // 禁止访问
	ProtoResponseCode_NOT_FOUND           ProtoResponseCode = 404 // 未找到
	ProtoResponseCode_INTERNAL_ERROR      ProtoResponseCode = 500 // 内部错误
	ProtoResponseCode_SERVICE_UNAVAILABLE ProtoResponseCode = 503 // 服务不可用
)

// Enum value maps for ProtoResponseCode.
var (
	ProtoResponseCode_name = map[int32]string{
		0:   "SUCCESS",
		400: "INVALID_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		500: "INTERNAL_ERROR",
		503: "SERVICE_UNAVAILABLE",
	}
	ProtoResponseCode_value = map[string]int32{
		"SUCCESS":             0,
		"INVALID_REQUEST":     400,
		"UNAUTHORIZED":        401,
		"FORBIDDEN":           403,
		"NOT_FOUND":           404,
		"INTERNAL_ERROR":      500,
		"SERVICE_UNAVAILABLE": 503,
	}
)

func (x ProtoResponseCode) Enum() *ProtoResponseCode {
	p := new(ProtoResponseCode)
	*p = x
	return p
}

func (x ProtoResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_service_proto_enumTypes[1].Descriptor()
}

func (ProtoResponseCode) Type() protoreflect.EnumType {
	return &file_proto_message_service_proto_enumTypes[1]
}

func (x ProtoResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoResponseCode.Descriptor instead.
func (ProtoResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{1}
}

// Web基础响应
type WebBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebBaseResponse) Reset() {
	*x = WebBaseResponse{}
	mi := &file_proto_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebBaseResponse) ProtoMessage() {}

func (x *WebBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebBaseResponse.ProtoReflect.Descriptor instead.
func (*WebBaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *WebBaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WebBaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WebBaseResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *WebBaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 基础消息包装（客户端->服务端）
type ImProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MsgType" json:"type,omitempty"` // 消息类型
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`            // 具体消息内容（根据type反序列化）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImProtoRequest) Reset() {
	*x = ImProtoRequest{}
	mi := &file_proto_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImProtoRequest) ProtoMessage() {}

func (x *ImProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImProtoRequest.ProtoReflect.Descriptor instead.
func (*ImProtoRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *ImProtoRequest) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_UNKNOWN
}

func (x *ImProtoRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 基础响应包装（服务端->客户端）
type ImProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MsgType" json:"type,omitempty"`           // 消息类型
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                      // 具体消息内容
	Code          ProtoResponseCode      `protobuf:"varint,3,opt,name=code,proto3,enum=pb.ProtoResponseCode" json:"code,omitempty"` // 响应码
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`                              // 错误消息（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImProtoResponse) Reset() {
	*x = ImProtoResponse{}
	mi := &file_proto_message_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImProtoResponse) ProtoMessage() {}

func (x *ImProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImProtoResponse.ProtoReflect.Descriptor instead.
func (*ImProtoResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{2}
}

func (x *ImProtoResponse) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_UNKNOWN
}

func (x *ImProtoResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImProtoResponse) GetCode() ProtoResponseCode {
	if x != nil {
		return x.Code
	}
	return ProtoResponseCode_SUCCESS
}

func (x *ImProtoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// C2C发送消息请求 - 上行（优化版）
type C2CSendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   []byte                 `protobuf:"bytes,1,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节，优化：string 36B -> bytes 16B）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 服务端消息ID（雪花算法，优化：string 19B -> fixed64 8B）
	From          uint64                 `protobuf:"fixed64,3,opt,name=from,proto3" json:"from,omitempty"`             // 发送人ID（雪花算法，优化：string 12B -> fixed64 8B）
	To            uint64                 `protobuf:"fixed64,4,opt,name=to,proto3" json:"to,omitempty"`                 // 接收人ID（雪花算法，优化：string 12B -> fixed64 8B）
	Format        int32                  `protobuf:"varint,5,opt,name=format,proto3" json:"format,omitempty"`          // 消息格式（1:文本,2:图片,3:语音等）
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`         // 消息内容
	Time          uint64                 `protobuf:"fixed64,7,opt,name=time,proto3" json:"time,omitempty"`             // 客户端时间戳（毫秒，优化：int64 -> fixed64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CSendReq) Reset() {
	*x = C2CSendReq{}
	mi := &file_proto_message_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CSendReq) ProtoMessage() {}

func (x *C2CSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CSendReq.ProtoReflect.Descriptor instead.
func (*C2CSendReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{3}
}

func (x *C2CSendReq) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *C2CSendReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CSendReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *C2CSendReq) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *C2CSendReq) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *C2CSendReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *C2CSendReq) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 客户端消息确认请求 - 上行（Go扩展）
type ClientReceivedMsgAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   []byte                 `protobuf:"bytes,1,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 服务端消息ID（雪花算法）
	Time          uint64                 `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`             // 确认时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReceivedMsgAck) Reset() {
	*x = ClientReceivedMsgAck{}
	mi := &file_proto_message_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReceivedMsgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReceivedMsgAck) ProtoMessage() {}

func (x *ClientReceivedMsgAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReceivedMsgAck.ProtoReflect.Descriptor instead.
func (*ClientReceivedMsgAck) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClientReceivedMsgAck) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *ClientReceivedMsgAck) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ClientReceivedMsgAck) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 撤回消息发送请求 - 上行（Go扩展）
type WithdrawMsgSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 要撤回的消息ID（雪花算法）
	ClientMsgId   []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节）
	Time          uint64                 `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`             // 撤回时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawMsgSend) Reset() {
	*x = WithdrawMsgSend{}
	mi := &file_proto_message_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawMsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMsgSend) ProtoMessage() {}

func (x *WithdrawMsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMsgSend.ProtoReflect.Descriptor instead.
func (*WithdrawMsgSend) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawMsgSend) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *WithdrawMsgSend) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *WithdrawMsgSend) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// C2C消息确认请求 - 上行（原版兼容）
type C2CAckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   []byte                 `protobuf:"bytes,1,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 服务端消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,3,opt,name=from,proto3" json:"from,omitempty"`             // 发送人ID（雪花算法）
	To            uint64                 `protobuf:"fixed64,4,opt,name=to,proto3" json:"to,omitempty"`                 // 接收人ID（雪花算法）
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`          // 消息状态（3:未读，4:已读）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CAckReq) Reset() {
	*x = C2CAckReq{}
	mi := &file_proto_message_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CAckReq) ProtoMessage() {}

func (x *C2CAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CAckReq.ProtoReflect.Descriptor instead.
func (*C2CAckReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{6}
}

func (x *C2CAckReq) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *C2CAckReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CAckReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *C2CAckReq) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *C2CAckReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// C2C撤回消息请求 - 上行（原版兼容）
type C2CWithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"` // 要撤回的消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`   // 发送人ID（雪花算法）
	To            uint64                 `protobuf:"fixed64,3,opt,name=to,proto3" json:"to,omitempty"`       // 接收人ID（雪花算法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CWithdrawReq) Reset() {
	*x = C2CWithdrawReq{}
	mi := &file_proto_message_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CWithdrawReq) ProtoMessage() {}

func (x *C2CWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CWithdrawReq.ProtoReflect.Descriptor instead.
func (*C2CWithdrawReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{7}
}

func (x *C2CWithdrawReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CWithdrawReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *C2CWithdrawReq) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

// 批量获取消息ID请求 - 上行（优化版）
type GetBatchMsgIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"fixed64,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID（雪花算法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchMsgIdsReq) Reset() {
	*x = GetBatchMsgIdsReq{}
	mi := &file_proto_message_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchMsgIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchMsgIdsReq) ProtoMessage() {}

func (x *GetBatchMsgIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchMsgIdsReq.ProtoReflect.Descriptor instead.
func (*GetBatchMsgIdsReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetBatchMsgIdsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 服务端推送C2C消息 - 下行（优化版）
type C2CMsgPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   []byte                 `protobuf:"bytes,1,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 服务端消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,3,opt,name=from,proto3" json:"from,omitempty"`             // 发送人ID（雪花算法）
	To            uint64                 `protobuf:"fixed64,4,opt,name=to,proto3" json:"to,omitempty"`                 // 接收人ID（雪花算法）
	Format        int32                  `protobuf:"varint,5,opt,name=format,proto3" json:"format,omitempty"`          // 消息格式
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`         // 消息内容
	Time          uint64                 `protobuf:"fixed64,7,opt,name=time,proto3" json:"time,omitempty"`             // 服务器时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CMsgPush) Reset() {
	*x = C2CMsgPush{}
	mi := &file_proto_message_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CMsgPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CMsgPush) ProtoMessage() {}

func (x *C2CMsgPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CMsgPush.ProtoReflect.Descriptor instead.
func (*C2CMsgPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{9}
}

func (x *C2CMsgPush) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *C2CMsgPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CMsgPush) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *C2CMsgPush) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *C2CMsgPush) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *C2CMsgPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *C2CMsgPush) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// C2C 消息结构体（用于历史查询等）
type C2CMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`            // 消息ID
	From          uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`              // 发送人ID
	To            uint64                 `protobuf:"fixed64,3,opt,name=to,proto3" json:"to,omitempty"`                  // 接收人ID
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`          // 消息内容
	Format        int32                  `protobuf:"varint,5,opt,name=format,proto3" json:"format,omitempty"`           // 消息格式
	SendTime      uint64                 `protobuf:"fixed64,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`      // 发送时间
	IsWithdrawn   bool                   `protobuf:"varint,7,opt,name=isWithdrawn,proto3" json:"isWithdrawn,omitempty"` // 是否已撤回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CMessage) Reset() {
	*x = C2CMessage{}
	mi := &file_proto_message_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CMessage) ProtoMessage() {}

func (x *C2CMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CMessage.ProtoReflect.Descriptor instead.
func (*C2CMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{10}
}

func (x *C2CMessage) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *C2CMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *C2CMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *C2CMessage) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *C2CMessage) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *C2CMessage) GetIsWithdrawn() bool {
	if x != nil {
		return x.IsWithdrawn
	}
	return false
}

// 服务器确认消息 - 下行（Go扩展）
type ServerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   []byte                 `protobuf:"bytes,1,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID（UUID 16字节）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 服务端消息ID（雪花算法）
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`        // 是否成功
	Timestamp     uint64                 `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAck) Reset() {
	*x = ServerAck{}
	mi := &file_proto_message_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAck) ProtoMessage() {}

func (x *ServerAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAck.ProtoReflect.Descriptor instead.
func (*ServerAck) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{11}
}

func (x *ServerAck) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *ServerAck) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ServerAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 消息送达通知 - 下行（Go扩展）
type MessageDeliveryNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`             // 消息ID
	ClientMsgId   []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`   // 客户端消息ID
	DeliveredAt   uint64                 `protobuf:"fixed64,3,opt,name=deliveredAt,proto3" json:"deliveredAt,omitempty"` // 送达时间
	ReceiverAck   bool                   `protobuf:"varint,4,opt,name=receiverAck,proto3" json:"receiverAck,omitempty"`  // 接收方确认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeliveryNotification) Reset() {
	*x = MessageDeliveryNotification{}
	mi := &file_proto_message_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeliveryNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeliveryNotification) ProtoMessage() {}

func (x *MessageDeliveryNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeliveryNotification.ProtoReflect.Descriptor instead.
func (*MessageDeliveryNotification) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{12}
}

func (x *MessageDeliveryNotification) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageDeliveryNotification) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *MessageDeliveryNotification) GetDeliveredAt() uint64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

func (x *MessageDeliveryNotification) GetReceiverAck() bool {
	if x != nil {
		return x.ReceiverAck
	}
	return false
}

// 消息撤回通知 - 下行（Go扩展）
type MessageWithdrawNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MsgId           uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`                   // 消息ID
	ClientMsgId     []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`         // 客户端消息ID
	WithdrawnAt     uint64                 `protobuf:"fixed64,3,opt,name=withdrawnAt,proto3" json:"withdrawnAt,omitempty"`       // 撤回时间
	WithdrawnBy     uint64                 `protobuf:"fixed64,4,opt,name=withdrawnBy,proto3" json:"withdrawnBy,omitempty"`       // 撤回者ID
	OriginalContent string                 `protobuf:"bytes,5,opt,name=originalContent,proto3" json:"originalContent,omitempty"` // 撤回提示文本
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageWithdrawNotification) Reset() {
	*x = MessageWithdrawNotification{}
	mi := &file_proto_message_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithdrawNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithdrawNotification) ProtoMessage() {}

func (x *MessageWithdrawNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithdrawNotification.ProtoReflect.Descriptor instead.
func (*MessageWithdrawNotification) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{13}
}

func (x *MessageWithdrawNotification) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageWithdrawNotification) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *MessageWithdrawNotification) GetWithdrawnAt() uint64 {
	if x != nil {
		return x.WithdrawnAt
	}
	return 0
}

func (x *MessageWithdrawNotification) GetWithdrawnBy() uint64 {
	if x != nil {
		return x.WithdrawnBy
	}
	return 0
}

func (x *MessageWithdrawNotification) GetOriginalContent() string {
	if x != nil {
		return x.OriginalContent
	}
	return ""
}

// 撤回消息响应 - 下行（Go扩展）
type WithdrawMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 消息ID
	ClientMsgId   []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"` // 客户端消息ID
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`        // 是否成功
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`         // 响应消息
	Timestamp     uint64                 `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawMsgResponse) Reset() {
	*x = WithdrawMsgResponse{}
	mi := &file_proto_message_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMsgResponse) ProtoMessage() {}

func (x *WithdrawMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMsgResponse.ProtoReflect.Descriptor instead.
func (*WithdrawMsgResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawMsgResponse) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *WithdrawMsgResponse) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *WithdrawMsgResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawMsgResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WithdrawMsgResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 批量消息ID推送 - 下行（优化版）
type BatchMsgIdsPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgIds        []uint64               `protobuf:"fixed64,1,rep,packed,name=msgIds,proto3" json:"msgIds,omitempty"` // 消息ID列表（雪花算法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMsgIdsPush) Reset() {
	*x = BatchMsgIdsPush{}
	mi := &file_proto_message_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMsgIdsPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMsgIdsPush) ProtoMessage() {}

func (x *BatchMsgIdsPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMsgIdsPush.ProtoReflect.Descriptor instead.
func (*BatchMsgIdsPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{15}
}

func (x *BatchMsgIdsPush) GetMsgIds() []uint64 {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

// 服务端ACK推送 - 下行（gRPC专用，优化版）
type ServerAckPush struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ToUserId          uint64                 `protobuf:"fixed64,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`                  // 接收人ID（雪花算法）
	ClientMsgId       []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`              // 客户端消息ID（UUID 16字节）
	MsgId             uint64                 `protobuf:"fixed64,3,opt,name=msgId,proto3" json:"msgId,omitempty"`                        // 服务端消息ID（雪花算法）
	MsgReceivedStatus int32                  `protobuf:"varint,5,opt,name=msgReceivedStatus,proto3" json:"msgReceivedStatus,omitempty"` // 1=SERVER_RECEIVED
	ReceiveTime       uint64                 `protobuf:"fixed64,7,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`            // 接收时间戳（毫秒）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerAckPush) Reset() {
	*x = ServerAckPush{}
	mi := &file_proto_message_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAckPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAckPush) ProtoMessage() {}

func (x *ServerAckPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAckPush.ProtoReflect.Descriptor instead.
func (*ServerAckPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{16}
}

func (x *ServerAckPush) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ServerAckPush) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *ServerAckPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ServerAckPush) GetMsgReceivedStatus() int32 {
	if x != nil {
		return x.MsgReceivedStatus
	}
	return 0
}

func (x *ServerAckPush) GetReceiveTime() uint64 {
	if x != nil {
		return x.ReceiveTime
	}
	return 0
}

// 客户端ACK推送 - 下行（gRPC专用，优化版）
type ClientAckPush struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ToUserId          uint64                 `protobuf:"fixed64,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`                  // 接收人ID（雪花算法）
	ClientMsgId       []byte                 `protobuf:"bytes,2,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`              // 客户端消息ID（UUID 16字节）
	MsgId             uint64                 `protobuf:"fixed64,3,opt,name=msgId,proto3" json:"msgId,omitempty"`                        // 服务端消息ID（雪花算法）
	MsgReceivedStatus int32                  `protobuf:"varint,5,opt,name=msgReceivedStatus,proto3" json:"msgReceivedStatus,omitempty"` // 3=UN_READ, 4=READED
	ReceiveTime       uint64                 `protobuf:"fixed64,7,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`            // 接收时间戳（毫秒）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientAckPush) Reset() {
	*x = ClientAckPush{}
	mi := &file_proto_message_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAckPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAckPush) ProtoMessage() {}

func (x *ClientAckPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAckPush.ProtoReflect.Descriptor instead.
func (*ClientAckPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{17}
}

func (x *ClientAckPush) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ClientAckPush) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *ClientAckPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ClientAckPush) GetMsgReceivedStatus() int32 {
	if x != nil {
		return x.MsgReceivedStatus
	}
	return 0
}

func (x *ClientAckPush) GetReceiveTime() uint64 {
	if x != nil {
		return x.ReceiveTime
	}
	return 0
}

// 撤回消息推送 - 下行（gRPC专用，优化版）
type WithdrawPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      uint64                 `protobuf:"fixed64,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`     // 接收人ID（雪花算法）
	MsgId         uint64                 `protobuf:"fixed64,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // 消息ID（雪花算法）
	FromUserId    uint64                 `protobuf:"fixed64,4,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"` // 发送人ID（雪花算法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawPush) Reset() {
	*x = WithdrawPush{}
	mi := &file_proto_message_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawPush) ProtoMessage() {}

func (x *WithdrawPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawPush.ProtoReflect.Descriptor instead.
func (*WithdrawPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawPush) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *WithdrawPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *WithdrawPush) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

// 好友请求推送 - 下行（gRPC专用，优化版）
type FriendRequestPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToUserId       uint64                 `protobuf:"fixed64,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`           // 接收人ID（雪花算法）
	RequestId      []byte                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`           // 请求ID（UUID，16字节）
	FromUserId     uint64                 `protobuf:"fixed64,3,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`       // 申请人ID（雪花算法）
	FromUserName   string                 `protobuf:"bytes,4,opt,name=fromUserName,proto3" json:"fromUserName,omitempty"`     // 申请人昵称
	FromUserAvatar string                 `protobuf:"bytes,5,opt,name=fromUserAvatar,proto3" json:"fromUserAvatar,omitempty"` // 申请人头像
	RequestMessage string                 `protobuf:"bytes,6,opt,name=requestMessage,proto3" json:"requestMessage,omitempty"` // 申请消息
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                // 状态：0=待处理, 1=已同意, 2=已拒绝
	CreateTime     uint64                 `protobuf:"fixed64,8,opt,name=createTime,proto3" json:"createTime,omitempty"`       // 创建时间（毫秒）
	PushTitle      string                 `protobuf:"bytes,9,opt,name=pushTitle,proto3" json:"pushTitle,omitempty"`           // 推送标题
	PushContent    string                 `protobuf:"bytes,10,opt,name=pushContent,proto3" json:"pushContent,omitempty"`      // 推送内容
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRequestPush) Reset() {
	*x = FriendRequestPush{}
	mi := &file_proto_message_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestPush) ProtoMessage() {}

func (x *FriendRequestPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestPush.ProtoReflect.Descriptor instead.
func (*FriendRequestPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{19}
}

func (x *FriendRequestPush) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendRequestPush) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *FriendRequestPush) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequestPush) GetFromUserName() string {
	if x != nil {
		return x.FromUserName
	}
	return ""
}

func (x *FriendRequestPush) GetFromUserAvatar() string {
	if x != nil {
		return x.FromUserAvatar
	}
	return ""
}

func (x *FriendRequestPush) GetRequestMessage() string {
	if x != nil {
		return x.RequestMessage
	}
	return ""
}

func (x *FriendRequestPush) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestPush) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FriendRequestPush) GetPushTitle() string {
	if x != nil {
		return x.PushTitle
	}
	return ""
}

func (x *FriendRequestPush) GetPushContent() string {
	if x != nil {
		return x.PushContent
	}
	return ""
}

// 好友响应推送 - 下行（gRPC专用，优化版）
type FriendResponsePush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToUserId       uint64                 `protobuf:"fixed64,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`           // 接收人ID（雪花算法）
	RequestId      []byte                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`           // 请求ID（UUID，16字节）
	FromUserId     uint64                 `protobuf:"fixed64,3,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`       // 响应人ID（雪花算法）
	FromUserName   string                 `protobuf:"bytes,4,opt,name=fromUserName,proto3" json:"fromUserName,omitempty"`     // 响应人昵称
	FromUserAvatar string                 `protobuf:"bytes,5,opt,name=fromUserAvatar,proto3" json:"fromUserAvatar,omitempty"` // 响应人头像
	Status         int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                // 状态：1=已同意, 2=已拒绝
	ResponseTime   uint64                 `protobuf:"fixed64,7,opt,name=responseTime,proto3" json:"responseTime,omitempty"`   // 响应时间（毫秒）
	PushTitle      string                 `protobuf:"bytes,8,opt,name=pushTitle,proto3" json:"pushTitle,omitempty"`           // 推送标题
	PushContent    string                 `protobuf:"bytes,9,opt,name=pushContent,proto3" json:"pushContent,omitempty"`       // 推送内容
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendResponsePush) Reset() {
	*x = FriendResponsePush{}
	mi := &file_proto_message_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendResponsePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendResponsePush) ProtoMessage() {}

func (x *FriendResponsePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendResponsePush.ProtoReflect.Descriptor instead.
func (*FriendResponsePush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{20}
}

func (x *FriendResponsePush) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendResponsePush) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *FriendResponsePush) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendResponsePush) GetFromUserName() string {
	if x != nil {
		return x.FromUserName
	}
	return ""
}

func (x *FriendResponsePush) GetFromUserAvatar() string {
	if x != nil {
		return x.FromUserAvatar
	}
	return ""
}

func (x *FriendResponsePush) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendResponsePush) GetResponseTime() uint64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *FriendResponsePush) GetPushTitle() string {
	if x != nil {
		return x.PushTitle
	}
	return ""
}

func (x *FriendResponsePush) GetPushContent() string {
	if x != nil {
		return x.PushContent
	}
	return ""
}

// 群聊发送消息请求 - 上行（优化版，预留）
type GroupSendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`     // 消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`       // 发送人ID（雪花算法）
	GroupId       uint64                 `protobuf:"fixed64,3,opt,name=groupId,proto3" json:"groupId,omitempty"` // 群ID（雪花算法）
	Format        int32                  `protobuf:"varint,4,opt,name=format,proto3" json:"format,omitempty"`    // 消息格式（1:文本,2:图片,3:语音等）
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`   // 消息内容
	Time          uint64                 `protobuf:"fixed64,6,opt,name=time,proto3" json:"time,omitempty"`       // 客户端时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSendReq) Reset() {
	*x = GroupSendReq{}
	mi := &file_proto_message_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSendReq) ProtoMessage() {}

func (x *GroupSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSendReq.ProtoReflect.Descriptor instead.
func (*GroupSendReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{21}
}

func (x *GroupSendReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupSendReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GroupSendReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSendReq) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *GroupSendReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupSendReq) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 群聊消息推送 - 下行（优化版，预留）
type GroupMsgPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`             // 消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`               // 发送人ID（雪花算法）
	FromNickname  string                 `protobuf:"bytes,3,opt,name=fromNickname,proto3" json:"fromNickname,omitempty"` // 发送人昵称（群聊显示用）
	FromAvatar    string                 `protobuf:"bytes,4,opt,name=fromAvatar,proto3" json:"fromAvatar,omitempty"`     // 发送人头像（群聊显示用）
	GroupId       uint64                 `protobuf:"fixed64,5,opt,name=groupId,proto3" json:"groupId,omitempty"`         // 群ID（雪花算法）
	GroupName     string                 `protobuf:"bytes,6,opt,name=groupName,proto3" json:"groupName,omitempty"`       // 群名称
	Format        int32                  `protobuf:"varint,7,opt,name=format,proto3" json:"format,omitempty"`            // 消息格式
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`           // 消息内容
	Time          uint64                 `protobuf:"fixed64,9,opt,name=time,proto3" json:"time,omitempty"`               // 服务器时间戳（毫秒）
	MemberCount   int32                  `protobuf:"varint,10,opt,name=memberCount,proto3" json:"memberCount,omitempty"` // 群成员数（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMsgPush) Reset() {
	*x = GroupMsgPush{}
	mi := &file_proto_message_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMsgPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMsgPush) ProtoMessage() {}

func (x *GroupMsgPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMsgPush.ProtoReflect.Descriptor instead.
func (*GroupMsgPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{22}
}

func (x *GroupMsgPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupMsgPush) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GroupMsgPush) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *GroupMsgPush) GetFromAvatar() string {
	if x != nil {
		return x.FromAvatar
	}
	return ""
}

func (x *GroupMsgPush) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMsgPush) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupMsgPush) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *GroupMsgPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupMsgPush) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GroupMsgPush) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

// 群聊消息确认请求 - 上行（优化版，预留）
type GroupAckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`     // 消息ID（雪花算法）
	UserId        uint64                 `protobuf:"fixed64,2,opt,name=userId,proto3" json:"userId,omitempty"`   // 确认人ID（雪花算法）
	GroupId       uint64                 `protobuf:"fixed64,3,opt,name=groupId,proto3" json:"groupId,omitempty"` // 群ID（雪花算法）
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`    // 消息状态（3:未读，4:已读）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAckReq) Reset() {
	*x = GroupAckReq{}
	mi := &file_proto_message_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAckReq) ProtoMessage() {}

func (x *GroupAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAckReq.ProtoReflect.Descriptor instead.
func (*GroupAckReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{23}
}

func (x *GroupAckReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupAckReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupAckReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupAckReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 群聊撤回消息请求 - 上行（优化版，预留）
type GroupWithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`               // 要撤回的消息ID（雪花算法）
	From          uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`                 // 发送人ID（雪花算法）
	GroupId       uint64                 `protobuf:"fixed64,3,opt,name=groupId,proto3" json:"groupId,omitempty"`           // 群ID（雪花算法）
	WithdrawTime  uint64                 `protobuf:"fixed64,4,opt,name=withdrawTime,proto3" json:"withdrawTime,omitempty"` // 撤回时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupWithdrawReq) Reset() {
	*x = GroupWithdrawReq{}
	mi := &file_proto_message_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupWithdrawReq) ProtoMessage() {}

func (x *GroupWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupWithdrawReq.ProtoReflect.Descriptor instead.
func (*GroupWithdrawReq) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{24}
}

func (x *GroupWithdrawReq) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupWithdrawReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GroupWithdrawReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupWithdrawReq) GetWithdrawTime() uint64 {
	if x != nil {
		return x.WithdrawTime
	}
	return 0
}

// 群聊撤回消息推送 - 下行（优化版，预留）
type GroupWithdrawPush struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MsgId            uint64                 `protobuf:"fixed64,1,opt,name=msgId,proto3" json:"msgId,omitempty"`                     // 被撤回的消息ID（雪花算法）
	From             uint64                 `protobuf:"fixed64,2,opt,name=from,proto3" json:"from,omitempty"`                       // 撤回操作人ID（雪花算法）
	GroupId          uint64                 `protobuf:"fixed64,3,opt,name=groupId,proto3" json:"groupId,omitempty"`                 // 群ID（雪花算法）
	OperatorNickname string                 `protobuf:"bytes,4,opt,name=operatorNickname,proto3" json:"operatorNickname,omitempty"` // 操作人昵称（用于显示"XXX撤回了一条消息"）
	WithdrawTime     uint64                 `protobuf:"fixed64,5,opt,name=withdrawTime,proto3" json:"withdrawTime,omitempty"`       // 撤回时间戳
	IsAdmin          bool                   `protobuf:"varint,6,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`                  // 是否为管理员撤回（true=管理员撤回他人消息）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupWithdrawPush) Reset() {
	*x = GroupWithdrawPush{}
	mi := &file_proto_message_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupWithdrawPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupWithdrawPush) ProtoMessage() {}

func (x *GroupWithdrawPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupWithdrawPush.ProtoReflect.Descriptor instead.
func (*GroupWithdrawPush) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{25}
}

func (x *GroupWithdrawPush) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupWithdrawPush) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GroupWithdrawPush) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupWithdrawPush) GetOperatorNickname() string {
	if x != nil {
		return x.OperatorNickname
	}
	return ""
}

func (x *GroupWithdrawPush) GetWithdrawTime() uint64 {
	if x != nil {
		return x.WithdrawTime
	}
	return 0
}

func (x *GroupWithdrawPush) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_proto_message_service_proto protoreflect.FileDescriptor

const file_proto_message_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message_service.proto\x12\x02pb\"m\n" +
	"\x0fWebBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"K\n" +
	"\x0eImProtoRequest\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\x0e2\v.pb.MsgTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x89\x01\n" +
	"\x0fImProtoResponse\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\x0e2\v.pb.MsgTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12)\n" +
	"\x04code\x18\x03 \x01(\x0e2\x15.pb.ProtoResponseCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"\xae\x01\n" +
	"\n" +
	"C2CSendReq\x12 \n" +
	"\vclientMsgId\x18\x01 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x06R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x06R\x02to\x12\x16\n" +
	"\x06format\x18\x05 \x01(\x05R\x06format\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\a \x01(\x06R\x04time\"b\n" +
	"\x14ClientReceivedMsgAck\x12 \n" +
	"\vclientMsgId\x18\x01 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x06R\x04time\"]\n" +
	"\x0fWithdrawMsgSend\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x06R\x04time\"\x7f\n" +
	"\tC2CAckReq\x12 \n" +
	"\vclientMsgId\x18\x01 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x06R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x06R\x02to\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"J\n" +
	"\x0eC2CWithdrawReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x06R\x02to\"+\n" +
	"\x11GetBatchMsgIdsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x06R\x06userId\"\xae\x01\n" +
	"\n" +
	"C2CMsgPush\x12 \n" +
	"\vclientMsgId\x18\x01 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x06R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x06R\x02to\x12\x16\n" +
	"\x06format\x18\x05 \x01(\x05R\x06format\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\a \x01(\x06R\x04time\"\xb6\x01\n" +
	"\n" +
	"C2CMessage\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x06R\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06format\x18\x05 \x01(\x05R\x06format\x12\x1a\n" +
	"\bsendTime\x18\x06 \x01(\x06R\bsendTime\x12 \n" +
	"\visWithdrawn\x18\a \x01(\bR\visWithdrawn\"{\n" +
	"\tServerAck\x12 \n" +
	"\vclientMsgId\x18\x01 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x06R\ttimestamp\"\x99\x01\n" +
	"\x1bMessageDeliveryNotification\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12 \n" +
	"\vdeliveredAt\x18\x03 \x01(\x06R\vdeliveredAt\x12 \n" +
	"\vreceiverAck\x18\x04 \x01(\bR\vreceiverAck\"\xc3\x01\n" +
	"\x1bMessageWithdrawNotification\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12 \n" +
	"\vwithdrawnAt\x18\x03 \x01(\x06R\vwithdrawnAt\x12 \n" +
	"\vwithdrawnBy\x18\x04 \x01(\x06R\vwithdrawnBy\x12(\n" +
	"\x0foriginalContent\x18\x05 \x01(\tR\x0foriginalContent\"\x9f\x01\n" +
	"\x13WithdrawMsgResponse\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x06R\ttimestamp\")\n" +
	"\x0fBatchMsgIdsPush\x12\x16\n" +
	"\x06msgIds\x18\x01 \x03(\x06R\x06msgIds\"\xb3\x01\n" +
	"\rServerAckPush\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\x06R\btoUserId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\x06R\x05msgId\x12,\n" +
	"\x11msgReceivedStatus\x18\x05 \x01(\x05R\x11msgReceivedStatus\x12 \n" +
	"\vreceiveTime\x18\a \x01(\x06R\vreceiveTime\"\xb3\x01\n" +
	"\rClientAckPush\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\x06R\btoUserId\x12 \n" +
	"\vclientMsgId\x18\x02 \x01(\fR\vclientMsgId\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\x06R\x05msgId\x12,\n" +
	"\x11msgReceivedStatus\x18\x05 \x01(\x05R\x11msgReceivedStatus\x12 \n" +
	"\vreceiveTime\x18\a \x01(\x06R\vreceiveTime\"`\n" +
	"\fWithdrawPush\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\x06R\btoUserId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x06R\x05msgId\x12\x1e\n" +
	"\n" +
	"fromUserId\x18\x04 \x01(\x06R\n" +
	"fromUserId\"\xd9\x02\n" +
	"\x11FriendRequestPush\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\x06R\btoUserId\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\fR\trequestId\x12\x1e\n" +
	"\n" +
	"fromUserId\x18\x03 \x01(\x06R\n" +
	"fromUserId\x12\"\n" +
	"\ffromUserName\x18\x04 \x01(\tR\ffromUserName\x12&\n" +
	"\x0efromUserAvatar\x18\x05 \x01(\tR\x0efromUserAvatar\x12&\n" +
	"\x0erequestMessage\x18\x06 \x01(\tR\x0erequestMessage\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x06R\n" +
	"createTime\x12\x1c\n" +
	"\tpushTitle\x18\t \x01(\tR\tpushTitle\x12 \n" +
	"\vpushContent\x18\n" +
	" \x01(\tR\vpushContent\"\xb6\x02\n" +
	"\x12FriendResponsePush\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\x06R\btoUserId\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\fR\trequestId\x12\x1e\n" +
	"\n" +
	"fromUserId\x18\x03 \x01(\x06R\n" +
	"fromUserId\x12\"\n" +
	"\ffromUserName\x18\x04 \x01(\tR\ffromUserName\x12&\n" +
	"\x0efromUserAvatar\x18\x05 \x01(\tR\x0efromUserAvatar\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\"\n" +
	"\fresponseTime\x18\a \x01(\x06R\fresponseTime\x12\x1c\n" +
	"\tpushTitle\x18\b \x01(\tR\tpushTitle\x12 \n" +
	"\vpushContent\x18\t \x01(\tR\vpushContent\"\x98\x01\n" +
	"\fGroupSendReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x06R\agroupId\x12\x16\n" +
	"\x06format\x18\x04 \x01(\x05R\x06format\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\x06 \x01(\x06R\x04time\"\x9c\x02\n" +
	"\fGroupMsgPush\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\"\n" +
	"\ffromNickname\x18\x03 \x01(\tR\ffromNickname\x12\x1e\n" +
	"\n" +
	"fromAvatar\x18\x04 \x01(\tR\n" +
	"fromAvatar\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x06R\agroupId\x12\x1c\n" +
	"\tgroupName\x18\x06 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06format\x18\a \x01(\x05R\x06format\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\t \x01(\x06R\x04time\x12 \n" +
	"\vmemberCount\x18\n" +
	" \x01(\x05R\vmemberCount\"m\n" +
	"\vGroupAckReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x06R\x06userId\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x06R\agroupId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"z\n" +
	"\x10GroupWithdrawReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x06R\agroupId\x12\"\n" +
	"\fwithdrawTime\x18\x04 \x01(\x06R\fwithdrawTime\"\xc1\x01\n" +
	"\x11GroupWithdrawPush\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x06R\x04from\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x06R\agroupId\x12*\n" +
	"\x10operatorNickname\x18\x04 \x01(\tR\x10operatorNickname\x12\"\n" +
	"\fwithdrawTime\x18\x05 \x01(\x06R\fwithdrawTime\x12\x18\n" +
	"\aisAdmin\x18\x06 \x01(\bR\aisAdmin*\xa9\x03\n" +
	"\aMsgType\x12\x14\n" +
	"\x10MSG_TYPE_UNKNOWN\x10\x00\x12\f\n" +
	"\bC2C_SEND\x10\x01\x12\v\n" +
	"\aC2C_ACK\x10\x02\x12\x10\n" +
	"\fC2C_WITHDRAW\x10\x03\x12\x10\n" +
	"\fC2C_MSG_PUSH\x10\x05\x12\x1b\n" +
	"\x17CLIENT_RECEIVED_MSG_ACK\x10\r\x12\x15\n" +
	"\x11WITHDRAW_MSG_SEND\x10\x0e\x12\x19\n" +
	"\x15WITHDRAW_MSG_RESPONSE\x10\x0f\x12\x1d\n" +
	"\x19MSG_DELIVERY_NOTIFICATION\x10\x10\x12\x1d\n" +
	"\x19MSG_WITHDRAW_NOTIFICATION\x10\x11\x12\x0e\n" +
	"\n" +
	"SERVER_ACK\x10\x12\x12\r\n" +
	"\tHEARTBEAT\x10\x13\x12\x0e\n" +
	"\n" +
	"GROUP_SEND\x10\a\x12\x12\n" +
	"\x0eGROUP_MSG_PUSH\x10\b\x12\r\n" +
	"\tGROUP_ACK\x10\t\x12\x12\n" +
	"\x0eGROUP_WITHDRAW\x10\n" +
	"\x12\x12\n" +
	"\x0eFRIEND_REQUEST\x10\v\x12\x13\n" +
	"\x0fFRIEND_RESPONSE\x10\f\x12\x15\n" +
	"\x11GET_BATCH_MSG_IDS\x10\x04\x12\x16\n" +
	"\x12PUSH_BATCH_MSG_IDS\x10\x06*\x98\x01\n" +
	"\x11ProtoResponseCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x14\n" +
	"\x0fINVALID_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x032\xb2\x03\n" +
	"\x0eMessageService\x12D\n" +
	"\x18ResponseServerAck2Client\x12\x11.pb.ServerAckPush\x1a\x13.pb.WebBaseResponse\"\x00\x12D\n" +
	"\x18ResponseClientAck2Client\x12\x11.pb.ClientAckPush\x1a\x13.pb.WebBaseResponse\"\x00\x12A\n" +
	"\x16SendWithdrawMsg2Client\x12\x10.pb.WithdrawPush\x1a\x13.pb.WebBaseResponse\"\x00\x12H\n" +
	"\x18PushFriendRequest2Client\x12\x15.pb.FriendRequestPush\x1a\x13.pb.WebBaseResponse\"\x00\x12J\n" +
	"\x19PushFriendResponse2Client\x12\x16.pb.FriendResponsePush\x1a\x13.pb.WebBaseResponse\"\x00\x12;\n" +
	"\x0eTransferC2CMsg\x12\x12.pb.ImProtoRequest\x1a\x13.pb.WebBaseResponse\"\x00BD\n" +
	"\rcom.xzll.grpcB\x13MessageServiceProtoP\x01Z\x1cim-connect-go/internal/protob\x06proto3"

var (
	file_proto_message_service_proto_rawDescOnce sync.Once
	file_proto_message_service_proto_rawDescData []byte
)

func file_proto_message_service_proto_rawDescGZIP() []byte {
	file_proto_message_service_proto_rawDescOnce.Do(func() {
		file_proto_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_service_proto_rawDesc), len(file_proto_message_service_proto_rawDesc)))
	})
	return file_proto_message_service_proto_rawDescData
}

var file_proto_message_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_message_service_proto_goTypes = []any{
	(MsgType)(0),                        // 0: pb.MsgType
	(ProtoResponseCode)(0),              // 1: pb.ProtoResponseCode
	(*WebBaseResponse)(nil),             // 2: pb.WebBaseResponse
	(*ImProtoRequest)(nil),              // 3: pb.ImProtoRequest
	(*ImProtoResponse)(nil),             // 4: pb.ImProtoResponse
	(*C2CSendReq)(nil),                  // 5: pb.C2CSendReq
	(*ClientReceivedMsgAck)(nil),        // 6: pb.ClientReceivedMsgAck
	(*WithdrawMsgSend)(nil),             // 7: pb.WithdrawMsgSend
	(*C2CAckReq)(nil),                   // 8: pb.C2CAckReq
	(*C2CWithdrawReq)(nil),              // 9: pb.C2CWithdrawReq
	(*GetBatchMsgIdsReq)(nil),           // 10: pb.GetBatchMsgIdsReq
	(*C2CMsgPush)(nil),                  // 11: pb.C2CMsgPush
	(*C2CMessage)(nil),                  // 12: pb.C2CMessage
	(*ServerAck)(nil),                   // 13: pb.ServerAck
	(*MessageDeliveryNotification)(nil), // 14: pb.MessageDeliveryNotification
	(*MessageWithdrawNotification)(nil), // 15: pb.MessageWithdrawNotification
	(*WithdrawMsgResponse)(nil),         // 16: pb.WithdrawMsgResponse
	(*BatchMsgIdsPush)(nil),             // 17: pb.BatchMsgIdsPush
	(*ServerAckPush)(nil),               // 18: pb.ServerAckPush
	(*ClientAckPush)(nil),               // 19: pb.ClientAckPush
	(*WithdrawPush)(nil),                // 20: pb.WithdrawPush
	(*FriendRequestPush)(nil),           // 21: pb.FriendRequestPush
	(*FriendResponsePush)(nil),          // 22: pb.FriendResponsePush
	(*GroupSendReq)(nil),                // 23: pb.GroupSendReq
	(*GroupMsgPush)(nil),                // 24: pb.GroupMsgPush
	(*GroupAckReq)(nil),                 // 25: pb.GroupAckReq
	(*GroupWithdrawReq)(nil),            // 26: pb.GroupWithdrawReq
	(*GroupWithdrawPush)(nil),           // 27: pb.GroupWithdrawPush
}
var file_proto_message_service_proto_depIdxs = []int32{
	0,  // 0: pb.ImProtoRequest.type:type_name -> pb.MsgType
	0,  // 1: pb.ImProtoResponse.type:type_name -> pb.MsgType
	1,  // 2: pb.ImProtoResponse.code:type_name -> pb.ProtoResponseCode
	18, // 3: pb.MessageService.ResponseServerAck2Client:input_type -> pb.ServerAckPush
	19, // 4: pb.MessageService.ResponseClientAck2Client:input_type -> pb.ClientAckPush
	20, // 5: pb.MessageService.SendWithdrawMsg2Client:input_type -> pb.WithdrawPush
	21, // 6: pb.MessageService.PushFriendRequest2Client:input_type -> pb.FriendRequestPush
	22, // 7: pb.MessageService.PushFriendResponse2Client:input_type -> pb.FriendResponsePush
	3,  // 8: pb.MessageService.TransferC2CMsg:input_type -> pb.ImProtoRequest
	2,  // 9: pb.MessageService.ResponseServerAck2Client:output_type -> pb.WebBaseResponse
	2,  // 10: pb.MessageService.ResponseClientAck2Client:output_type -> pb.WebBaseResponse
	2,  // 11: pb.MessageService.SendWithdrawMsg2Client:output_type -> pb.WebBaseResponse
	2,  // 12: pb.MessageService.PushFriendRequest2Client:output_type -> pb.WebBaseResponse
	2,  // 13: pb.MessageService.PushFriendResponse2Client:output_type -> pb.WebBaseResponse
	2,  // 14: pb.MessageService.TransferC2CMsg:output_type -> pb.WebBaseResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_message_service_proto_init() }
func file_proto_message_service_proto_init() {
	if File_proto_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_service_proto_rawDesc), len(file_proto_message_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_service_proto_goTypes,
		DependencyIndexes: file_proto_message_service_proto_depIdxs,
		EnumInfos:         file_proto_message_service_proto_enumTypes,
		MessageInfos:      file_proto_message_service_proto_msgTypes,
	}.Build()
	File_proto_message_service_proto = out.File
	file_proto_message_service_proto_goTypes = nil
	file_proto_message_service_proto_depIdxs = nil
}
