// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a TEMPORARY stub file for compilation purposes.
// Run: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/message_service.proto
// to generate the actual gRPC code.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	// 推送服务端ACK到客户端（下行）
	ResponseServerAck2Client(ctx context.Context, in *ServerAckPush, opts ...grpc.CallOption) (*WebBaseResponse, error)
	// 推送客户端ACK到客户端（下行）
	ResponseClientAck2Client(ctx context.Context, in *ClientAckPush, opts ...grpc.CallOption) (*WebBaseResponse, error)
	// 推送撤回消息到客户端（下行）
	SendWithdrawMsg2Client(ctx context.Context, in *WithdrawPush, opts ...grpc.CallOption) (*WebBaseResponse, error)
	// 推送好友请求到客户端（下行）
	PushFriendRequest2Client(ctx context.Context, in *FriendRequestPush, opts ...grpc.CallOption) (*WebBaseResponse, error)
	// 推送好友响应到客户端（下行）
	PushFriendResponse2Client(ctx context.Context, in *FriendResponsePush, opts ...grpc.CallOption) (*WebBaseResponse, error)
	// 跨服务器转发 Protobuf 消息（上行转发）
	TransferC2CMsg(ctx context.Context, in *ImProtoRequest, opts ...grpc.CallOption) (*WebBaseResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) ResponseServerAck2Client(ctx context.Context, in *ServerAckPush, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/ResponseServerAck2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ResponseClientAck2Client(ctx context.Context, in *ClientAckPush, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/ResponseClientAck2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendWithdrawMsg2Client(ctx context.Context, in *WithdrawPush, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/SendWithdrawMsg2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PushFriendRequest2Client(ctx context.Context, in *FriendRequestPush, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/PushFriendRequest2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PushFriendResponse2Client(ctx context.Context, in *FriendResponsePush, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/PushFriendResponse2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) TransferC2CMsg(ctx context.Context, in *ImProtoRequest, opts ...grpc.CallOption) (*WebBaseResponse, error) {
	out := new(WebBaseResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageService/TransferC2CMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	// 推送服务端ACK到客户端（下行）
	ResponseServerAck2Client(context.Context, *ServerAckPush) (*WebBaseResponse, error)
	// 推送客户端ACK到客户端（下行）
	ResponseClientAck2Client(context.Context, *ClientAckPush) (*WebBaseResponse, error)
	// 推送撤回消息到客户端（下行）
	SendWithdrawMsg2Client(context.Context, *WithdrawPush) (*WebBaseResponse, error)
	// 推送好友请求到客户端（下行）
	PushFriendRequest2Client(context.Context, *FriendRequestPush) (*WebBaseResponse, error)
	// 推送好友响应到客户端（下行）
	PushFriendResponse2Client(context.Context, *FriendResponsePush) (*WebBaseResponse, error)
	// 跨服务器转发 Protobuf 消息（上行转发）
	TransferC2CMsg(context.Context, *ImProtoRequest) (*WebBaseResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) ResponseServerAck2Client(context.Context, *ServerAckPush) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResponseServerAck2Client not implemented")
}
func (UnimplementedMessageServiceServer) ResponseClientAck2Client(context.Context, *ClientAckPush) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResponseClientAck2Client not implemented")
}
func (UnimplementedMessageServiceServer) SendWithdrawMsg2Client(context.Context, *WithdrawPush) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWithdrawMsg2Client not implemented")
}
func (UnimplementedMessageServiceServer) PushFriendRequest2Client(context.Context, *FriendRequestPush) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushFriendRequest2Client not implemented")
}
func (UnimplementedMessageServiceServer) PushFriendResponse2Client(context.Context, *FriendResponsePush) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushFriendResponse2Client not implemented")
}
func (UnimplementedMessageServiceServer) TransferC2CMsg(context.Context, *ImProtoRequest) (*WebBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferC2CMsg not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_ResponseServerAck2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerAckPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ResponseServerAck2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/ResponseServerAck2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ResponseServerAck2Client(ctx, req.(*ServerAckPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ResponseClientAck2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientAckPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ResponseClientAck2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/ResponseClientAck2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ResponseClientAck2Client(ctx, req.(*ClientAckPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendWithdrawMsg2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendWithdrawMsg2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/SendWithdrawMsg2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendWithdrawMsg2Client(ctx, req.(*WithdrawPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PushFriendRequest2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequestPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PushFriendRequest2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/PushFriendRequest2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PushFriendRequest2Client(ctx, req.(*FriendRequestPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PushFriendResponse2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendResponsePush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PushFriendResponse2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/PushFriendResponse2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PushFriendResponse2Client(ctx, req.(*FriendResponsePush))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_TransferC2CMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).TransferC2CMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageService/TransferC2CMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).TransferC2CMsg(ctx, req.(*ImProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResponseServerAck2Client",
			Handler:    _MessageService_ResponseServerAck2Client_Handler,
		},
		{
			MethodName: "ResponseClientAck2Client",
			Handler:    _MessageService_ResponseClientAck2Client_Handler,
		},
		{
			MethodName: "SendWithdrawMsg2Client",
			Handler:    _MessageService_SendWithdrawMsg2Client_Handler,
		},
		{
			MethodName: "PushFriendRequest2Client",
			Handler:    _MessageService_PushFriendRequest2Client_Handler,
		},
		{
			MethodName: "PushFriendResponse2Client",
			Handler:    _MessageService_PushFriendResponse2Client_Handler,
		},
		{
			MethodName: "TransferC2CMsg",
			Handler:    _MessageService_TransferC2CMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message_service.proto",
}
